#!/usr/bin/env bash
set -euo pipefail

# make sure the directory is right
TOPDIR="$(cd "$(dirname "${BASH_SOURCE}")" && pwd)"
cd "$TOPDIR" || exit 1

export CC_UPDATE="./update"

# public pages
export PAGES="./pages"
# source pages
export SOURCE="./site"
# script directory
export SCRIPTS="./scripts"
# redirect link for subdir/index.html
export REDIR_SITE="https://coolcuber.com"

# local overrides
[ -e ".env" ] && source ".env"

# redirect string (overrides .env)
export REDIRECT="<meta http-equiv=\"refresh\" content=\"0; URL=$REDIR_SITE\">"

if [ x"$#" == x"0" ]; then
	echo "$0 takes at least 1 argument"
	exit 1
fi

scripts=()

for var in "$@"; do
	script="$SCRIPTS/$(basename "$SCRIPTS/$var")"
	if [[ ! $script =~ ^$SCRIPTS/[A-Za-z\-]+$ ]] || [ ! -f "$script" ] || [ ! -x "$script" ]; then
		echo "Unknown command: \"$var\"" >&2
		exit 1
	fi
	scripts+=($script)
done

for script in "${scripts[@]}"; do
	exec "$script"
done
