#!/usr/bin/env bash

# make sure the directory is right
TOPDIR="$(cd "$(dirname "${BASH_SOURCE}")" && pwd)"
cd "$TOPDIR" || exit 1

export CC_UPDATE="./update"

# public pages
export PAGES="./pages"
# source pages
export SOURCE="./site"
# script directory
export SCRIPTS="./scripts"
# redirect link for subdir/index.html
export REDIR_SITE="https://coolcuber.com"

# local overrides
[ -e ".env" ] && source ".env"

# redirect string (overrides .env)
export REDIRECT="<meta http-equiv=\"refresh\" content=\"0; URL=$REDIR_SITE\">"

if [ x"$#" != x"1" ]; then
	echo "$0 takes exactly 1 argument ("pages" or "redirects")"
	exit 1
fi

case $1 in
	pages) exec "$SCRIPTS/pages";;
	redirects) exec "$SCRIPTS/redirects";;
	*) echo "Unknown option: \"$1\"" >&2;
		exit 1;;
esac
